package com.druid.entity;

import java.math.BigDecimal;
import java.util.Date;

public class IctLoanProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.policy_no
     *
     * @mbggenerated
     */
    private String policyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.cust_name
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.id_type
     *
     * @mbggenerated
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.id_num
     *
     * @mbggenerated
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.contract_no
     *
     * @mbggenerated
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.apply_code
     *
     * @mbggenerated
     */
    private String applyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.borrow_no
     *
     * @mbggenerated
     */
    private String borrowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.bank
     *
     * @mbggenerated
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.loan_time
     *
     * @mbggenerated
     */
    private Integer loanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.loan_amt
     *
     * @mbggenerated
     */
    private BigDecimal loanAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.loan_term
     *
     * @mbggenerated
     */
    private Integer loanTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.premium_rate
     *
     * @mbggenerated
     */
    private BigDecimal premiumRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.loan_rate
     *
     * @mbggenerated
     */
    private BigDecimal loanRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.loan_due_date
     *
     * @mbggenerated
     */
    private Integer loanDueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.first_repay_date
     *
     * @mbggenerated
     */
    private Integer firstRepayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.per_sld_date
     *
     * @mbggenerated
     */
    private Integer perSldDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.per_premium
     *
     * @mbggenerated
     */
    private BigDecimal perPremium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.busi_system
     *
     * @mbggenerated
     */
    private String busiSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.need_amt
     *
     * @mbggenerated
     */
    private BigDecimal needAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.ph_premium_rate
     *
     * @mbggenerated
     */
    private BigDecimal phPremiumRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.first_pound_rate
     *
     * @mbggenerated
     */
    private BigDecimal firstPoundRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.per_pound_rate
     *
     * @mbggenerated
     */
    private BigDecimal perPoundRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.sld_first_pound
     *
     * @mbggenerated
     */
    private BigDecimal sldFirstPound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.sld_per_pound
     *
     * @mbggenerated
     */
    private BigDecimal sldPerPound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.loan_termx
     *
     * @mbggenerated
     */
    private Integer loanTermx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.loan_termy
     *
     * @mbggenerated
     */
    private Integer loanTermy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.need_amt_x
     *
     * @mbggenerated
     */
    private BigDecimal needAmtX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.need_amt_y
     *
     * @mbggenerated
     */
    private BigDecimal needAmtY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.need_premium_x
     *
     * @mbggenerated
     */
    private BigDecimal needPremiumX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.need_premium_y
     *
     * @mbggenerated
     */
    private BigDecimal needPremiumY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ict_loan_property.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.id
     *
     * @return the value of ict_loan_property.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.id
     *
     * @param id the value for ict_loan_property.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.policy_no
     *
     * @return the value of ict_loan_property.policy_no
     *
     * @mbggenerated
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.policy_no
     *
     * @param policyNo the value for ict_loan_property.policy_no
     *
     * @mbggenerated
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo == null ? null : policyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.cust_name
     *
     * @return the value of ict_loan_property.cust_name
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.cust_name
     *
     * @param custName the value for ict_loan_property.cust_name
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.id_type
     *
     * @return the value of ict_loan_property.id_type
     *
     * @mbggenerated
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.id_type
     *
     * @param idType the value for ict_loan_property.id_type
     *
     * @mbggenerated
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.id_num
     *
     * @return the value of ict_loan_property.id_num
     *
     * @mbggenerated
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.id_num
     *
     * @param idNum the value for ict_loan_property.id_num
     *
     * @mbggenerated
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.contract_no
     *
     * @return the value of ict_loan_property.contract_no
     *
     * @mbggenerated
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.contract_no
     *
     * @param contractNo the value for ict_loan_property.contract_no
     *
     * @mbggenerated
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.apply_code
     *
     * @return the value of ict_loan_property.apply_code
     *
     * @mbggenerated
     */
    public String getApplyCode() {
        return applyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.apply_code
     *
     * @param applyCode the value for ict_loan_property.apply_code
     *
     * @mbggenerated
     */
    public void setApplyCode(String applyCode) {
        this.applyCode = applyCode == null ? null : applyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.borrow_no
     *
     * @return the value of ict_loan_property.borrow_no
     *
     * @mbggenerated
     */
    public String getBorrowNo() {
        return borrowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.borrow_no
     *
     * @param borrowNo the value for ict_loan_property.borrow_no
     *
     * @mbggenerated
     */
    public void setBorrowNo(String borrowNo) {
        this.borrowNo = borrowNo == null ? null : borrowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.bank
     *
     * @return the value of ict_loan_property.bank
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.bank
     *
     * @param bank the value for ict_loan_property.bank
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.loan_time
     *
     * @return the value of ict_loan_property.loan_time
     *
     * @mbggenerated
     */
    public Integer getLoanTime() {
        return loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.loan_time
     *
     * @param loanTime the value for ict_loan_property.loan_time
     *
     * @mbggenerated
     */
    public void setLoanTime(Integer loanTime) {
        this.loanTime = loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.loan_amt
     *
     * @return the value of ict_loan_property.loan_amt
     *
     * @mbggenerated
     */
    public BigDecimal getLoanAmt() {
        return loanAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.loan_amt
     *
     * @param loanAmt the value for ict_loan_property.loan_amt
     *
     * @mbggenerated
     */
    public void setLoanAmt(BigDecimal loanAmt) {
        this.loanAmt = loanAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.loan_term
     *
     * @return the value of ict_loan_property.loan_term
     *
     * @mbggenerated
     */
    public Integer getLoanTerm() {
        return loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.loan_term
     *
     * @param loanTerm the value for ict_loan_property.loan_term
     *
     * @mbggenerated
     */
    public void setLoanTerm(Integer loanTerm) {
        this.loanTerm = loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.premium_rate
     *
     * @return the value of ict_loan_property.premium_rate
     *
     * @mbggenerated
     */
    public BigDecimal getPremiumRate() {
        return premiumRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.premium_rate
     *
     * @param premiumRate the value for ict_loan_property.premium_rate
     *
     * @mbggenerated
     */
    public void setPremiumRate(BigDecimal premiumRate) {
        this.premiumRate = premiumRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.loan_rate
     *
     * @return the value of ict_loan_property.loan_rate
     *
     * @mbggenerated
     */
    public BigDecimal getLoanRate() {
        return loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.loan_rate
     *
     * @param loanRate the value for ict_loan_property.loan_rate
     *
     * @mbggenerated
     */
    public void setLoanRate(BigDecimal loanRate) {
        this.loanRate = loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.loan_due_date
     *
     * @return the value of ict_loan_property.loan_due_date
     *
     * @mbggenerated
     */
    public Integer getLoanDueDate() {
        return loanDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.loan_due_date
     *
     * @param loanDueDate the value for ict_loan_property.loan_due_date
     *
     * @mbggenerated
     */
    public void setLoanDueDate(Integer loanDueDate) {
        this.loanDueDate = loanDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.first_repay_date
     *
     * @return the value of ict_loan_property.first_repay_date
     *
     * @mbggenerated
     */
    public Integer getFirstRepayDate() {
        return firstRepayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.first_repay_date
     *
     * @param firstRepayDate the value for ict_loan_property.first_repay_date
     *
     * @mbggenerated
     */
    public void setFirstRepayDate(Integer firstRepayDate) {
        this.firstRepayDate = firstRepayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.per_sld_date
     *
     * @return the value of ict_loan_property.per_sld_date
     *
     * @mbggenerated
     */
    public Integer getPerSldDate() {
        return perSldDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.per_sld_date
     *
     * @param perSldDate the value for ict_loan_property.per_sld_date
     *
     * @mbggenerated
     */
    public void setPerSldDate(Integer perSldDate) {
        this.perSldDate = perSldDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.per_premium
     *
     * @return the value of ict_loan_property.per_premium
     *
     * @mbggenerated
     */
    public BigDecimal getPerPremium() {
        return perPremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.per_premium
     *
     * @param perPremium the value for ict_loan_property.per_premium
     *
     * @mbggenerated
     */
    public void setPerPremium(BigDecimal perPremium) {
        this.perPremium = perPremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.busi_system
     *
     * @return the value of ict_loan_property.busi_system
     *
     * @mbggenerated
     */
    public String getBusiSystem() {
        return busiSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.busi_system
     *
     * @param busiSystem the value for ict_loan_property.busi_system
     *
     * @mbggenerated
     */
    public void setBusiSystem(String busiSystem) {
        this.busiSystem = busiSystem == null ? null : busiSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.need_amt
     *
     * @return the value of ict_loan_property.need_amt
     *
     * @mbggenerated
     */
    public BigDecimal getNeedAmt() {
        return needAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.need_amt
     *
     * @param needAmt the value for ict_loan_property.need_amt
     *
     * @mbggenerated
     */
    public void setNeedAmt(BigDecimal needAmt) {
        this.needAmt = needAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.ph_premium_rate
     *
     * @return the value of ict_loan_property.ph_premium_rate
     *
     * @mbggenerated
     */
    public BigDecimal getPhPremiumRate() {
        return phPremiumRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.ph_premium_rate
     *
     * @param phPremiumRate the value for ict_loan_property.ph_premium_rate
     *
     * @mbggenerated
     */
    public void setPhPremiumRate(BigDecimal phPremiumRate) {
        this.phPremiumRate = phPremiumRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.first_pound_rate
     *
     * @return the value of ict_loan_property.first_pound_rate
     *
     * @mbggenerated
     */
    public BigDecimal getFirstPoundRate() {
        return firstPoundRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.first_pound_rate
     *
     * @param firstPoundRate the value for ict_loan_property.first_pound_rate
     *
     * @mbggenerated
     */
    public void setFirstPoundRate(BigDecimal firstPoundRate) {
        this.firstPoundRate = firstPoundRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.per_pound_rate
     *
     * @return the value of ict_loan_property.per_pound_rate
     *
     * @mbggenerated
     */
    public BigDecimal getPerPoundRate() {
        return perPoundRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.per_pound_rate
     *
     * @param perPoundRate the value for ict_loan_property.per_pound_rate
     *
     * @mbggenerated
     */
    public void setPerPoundRate(BigDecimal perPoundRate) {
        this.perPoundRate = perPoundRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.sld_first_pound
     *
     * @return the value of ict_loan_property.sld_first_pound
     *
     * @mbggenerated
     */
    public BigDecimal getSldFirstPound() {
        return sldFirstPound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.sld_first_pound
     *
     * @param sldFirstPound the value for ict_loan_property.sld_first_pound
     *
     * @mbggenerated
     */
    public void setSldFirstPound(BigDecimal sldFirstPound) {
        this.sldFirstPound = sldFirstPound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.sld_per_pound
     *
     * @return the value of ict_loan_property.sld_per_pound
     *
     * @mbggenerated
     */
    public BigDecimal getSldPerPound() {
        return sldPerPound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.sld_per_pound
     *
     * @param sldPerPound the value for ict_loan_property.sld_per_pound
     *
     * @mbggenerated
     */
    public void setSldPerPound(BigDecimal sldPerPound) {
        this.sldPerPound = sldPerPound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.loan_termx
     *
     * @return the value of ict_loan_property.loan_termx
     *
     * @mbggenerated
     */
    public Integer getLoanTermx() {
        return loanTermx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.loan_termx
     *
     * @param loanTermx the value for ict_loan_property.loan_termx
     *
     * @mbggenerated
     */
    public void setLoanTermx(Integer loanTermx) {
        this.loanTermx = loanTermx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.loan_termy
     *
     * @return the value of ict_loan_property.loan_termy
     *
     * @mbggenerated
     */
    public Integer getLoanTermy() {
        return loanTermy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.loan_termy
     *
     * @param loanTermy the value for ict_loan_property.loan_termy
     *
     * @mbggenerated
     */
    public void setLoanTermy(Integer loanTermy) {
        this.loanTermy = loanTermy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.need_amt_x
     *
     * @return the value of ict_loan_property.need_amt_x
     *
     * @mbggenerated
     */
    public BigDecimal getNeedAmtX() {
        return needAmtX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.need_amt_x
     *
     * @param needAmtX the value for ict_loan_property.need_amt_x
     *
     * @mbggenerated
     */
    public void setNeedAmtX(BigDecimal needAmtX) {
        this.needAmtX = needAmtX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.need_amt_y
     *
     * @return the value of ict_loan_property.need_amt_y
     *
     * @mbggenerated
     */
    public BigDecimal getNeedAmtY() {
        return needAmtY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.need_amt_y
     *
     * @param needAmtY the value for ict_loan_property.need_amt_y
     *
     * @mbggenerated
     */
    public void setNeedAmtY(BigDecimal needAmtY) {
        this.needAmtY = needAmtY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.need_premium_x
     *
     * @return the value of ict_loan_property.need_premium_x
     *
     * @mbggenerated
     */
    public BigDecimal getNeedPremiumX() {
        return needPremiumX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.need_premium_x
     *
     * @param needPremiumX the value for ict_loan_property.need_premium_x
     *
     * @mbggenerated
     */
    public void setNeedPremiumX(BigDecimal needPremiumX) {
        this.needPremiumX = needPremiumX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.need_premium_y
     *
     * @return the value of ict_loan_property.need_premium_y
     *
     * @mbggenerated
     */
    public BigDecimal getNeedPremiumY() {
        return needPremiumY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.need_premium_y
     *
     * @param needPremiumY the value for ict_loan_property.need_premium_y
     *
     * @mbggenerated
     */
    public void setNeedPremiumY(BigDecimal needPremiumY) {
        this.needPremiumY = needPremiumY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.create_time
     *
     * @return the value of ict_loan_property.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.create_time
     *
     * @param createTime the value for ict_loan_property.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ict_loan_property.last_update_time
     *
     * @return the value of ict_loan_property.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ict_loan_property.last_update_time
     *
     * @param lastUpdateTime the value for ict_loan_property.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}