package com.druid.dao;

import com.druid.entity.IctLoanProperty;

public interface IctLoanPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ict_loan_property
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ict_loan_property
     *
     * @mbggenerated
     */
    int insert(IctLoanProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ict_loan_property
     *
     * @mbggenerated
     */
    int insertSelective(IctLoanProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ict_loan_property
     *
     * @mbggenerated
     */
    IctLoanProperty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ict_loan_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IctLoanProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ict_loan_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IctLoanProperty record);
}